### ISSUE TITLE
A new Kodi and libreelec user question on SUDO

### ISSUE THREAD

**Issue by TechLiam** [swetoast/steamlink-launcher#12]
Hi, there really sorry if this is a silly question or something I should ask somewhere else I'm very very new to Kodi and LibreELEC. I have used Linux before but only very basic stuff (Ubuntun mainly).

Anyway the issue I'm having is I have installed v0.0.6 of this repo onto the LibreELEC raspberry pi I have and went to run it from the UI of Kodi I got the following error message

```
 There is no working 'sudo'.

 On debian/ubuntu/all general purpose linux distributions 'sudo'
 allows a permitted user to execute a command as the superuser
 or another user, as specified by the security policy

 With LibreELEC you have root access by default, so you dont need 'sudo'
```

Now I get this same message when SSH'ed into the LibreELEC box and I try using SUDO anything so I might be an issue with LibreELEC that I have tried googleing for but not found much any advice or help would be very helpful.

**Comment by swetoast** [comment]
hi, you need to switch over to development instead of master and retry :I
