### ISSUE TITLE
Wake on LAN support

### ISSUE THREAD

**Issue by tacotexmex** [swetoast/steamlink-launcher#14]
I installed `wakeonlan` on my RPi3 and added a line in the launcher script to wake up the gaming machine on launch. Maybe this can be turned into a feature supported in the addon’s settings UI?

**Comment by swetoast** [comment]
Feel free to pr the stuff you got already

**Comment by swetoast** [comment]
https://github.com/swetoast/steamlink-launcher/tree/dev

**Comment by tacotexmex** [comment]
I just modified the shell script adding `wakeonlan 1a:2b:3c:4d:5f:6g` to it.

However, I’ve no idea on how to add UI support for it, nor is wakeonlan preinstalled on OSMC.

**Comment by swetoast** [comment]
Gonna add some if statements and a config file got an idea for it

**Comment by swetoast** [comment]
added
