### ISSUE TITLE
The dependency on xbmc.python version 3.0.0 could not be satisfied.

### ISSUE THREAD

**Issue by ceisma** [swetoast/steamlink-launcher#15]
I tried to install the latest dev version and it gives me an error when I want to start Steamlink via Kodi.
I'm using the latest version of LibreElec (9.2.3) with Kodi 18.7.1 on a Rpi 3.

I guess the reason for this error message is that Py3 is not supported because Kodi 18 is using Py2.
The master version of Steamlink seems to work with Py2 according to addon.xml. So that seems fine.

**Comment by swetoast** [comment]
use dev branch

**Comment by ceisma** [comment]
As I mentioned in my previous comment I used the dev branch.

**Comment by swetoast** [comment]
im not backporting to kodi 18 only 19 since py2 is being shutdown

**Comment by ceisma** [comment]
Understandable. Then I will wait when LibreElec will make the jump to kodi 19.

Thank you for your quick reply.
