### ISSUE TITLE
New Steam Link version

### ISSUE THREAD

**Issue by protist** [swetoast/steamlink-launcher#19]
How does this add-on relate to the new (I think?) version of Steam Link released recently? `steamlink-launcher` [seems to](https://github.com/swetoast/steamlink-launcher/blob/master/plugin.program.steamlink/addon.py#L50) download Steam Link directly from [media.steampowered.com](http://media.steampowered.com/steamlink/rpi/steamlink.deb), which is currently version 1.0.8. I checked my install, and this hasn't been updated since at least March 2019.

However, Valve have now released a new version 1.1.73.179 [on Flathub](https://flathub.org/apps/details/com.valvesoftware.SteamLink). Is this new version available for OSMC, and if so, should `steamlink-launcher` install this instead?

**Comment by swetoast** [comment]
and once you start the app it autoupdates to the latest version

**Comment by protist** [comment]
Ahhh… thank you! TBH I installed this once, the performance was very bad (it kept crashing), and so I never tried again. I started Steam Link again, and indeed it started installing 1.1.73.179.

I can see this version installed via GUI info, but the package manager only sees the old version. Do you know how it was installed?

```
$ apt list steamlink
Listing... Done
steamlink/now 1.0.8 armhf [installed,local]
```

**Comment by swetoast** [comment]
its the default package Valve has but once installed it auto updates so ignore package version

**Comment by protist** [comment]
Oh great! Thank again. I was worried that these files weren't being tracked by the package manager, but I had a closer look and it seems like the updated files are being installed in `~/.local/share/SteamLink` by Valve. Pretty weird, but I guess it's the simplest option. Thanks!
