### ISSUE TITLE
Invalid zip structure

### ISSUE THREAD

**Issue by win8linux** [swetoast/steamlink-launcher#2]
Hello there! The ZIP file is not being accepted by OSMC since the structure is invalid. It was downloaded through SSH using this command:

```sh
wget -c https://github.com/swetoast/steamlink-launcher/releases/download/0.0.3/plugin.program.steamlink-v.0.0.3.zip
```

**Comment by swetoast** [comment]
yeah i know i am gonna fix it when i get some time over

**Comment by swetoast** [comment]
try the new zip should address the issue :) install it via Kodi under the install menu for addons
