### ISSUE TITLE
Can't install addon on OSMC 2020.11-1 due to invalid structure

### ISSUE THREAD

**Issue by NinjaXI** [swetoast/steamlink-launcher#21]
Hi

I am running OSMC 2020.11-1 that runs on Kodi 18.9. If I try to install the addon from zip file I get an error
message saying "Installing the Add-on from zip file located at /media/UBUNTU 2019_1/plugin.program.steamlink-v0.0.7a.zip failed due to an invalid structure".

Similarly the only entry in my logs relating to this addon reads as follows : 
`2021-03-19 10:39:35.539 T:1916514320   ERROR: Failed to read 'zip://%2fmedia%2fUBUNTU%2019_1%2fplugin.program.steamlink-v0.0.7a.zip/plugin.program.steamlink-v0.0.7a/addon.xml'`

After seeing the above I did try renaming the folder in the zip from plugin.program.steamlink to plugin.program.steamlink-v0.0.7a, but no dice. I also noticed in the addon.xml there is an extra " after the version on line 4, `<import addon="xbmc.python" version="3.0.0""/>`, but fixing that also did not fix my problem.

**Comment by swetoast** [comment]
so that is just for kodi 19 thats why

**Comment by NinjaXI** [comment]
I noticed this shortly after I opened the issue as I was unaware OSMC 2020.11-1 was running on Kodi 18 until I went looking for it for this issue. Apologies for the noise.
