### ISSUE TITLE
Line 4 error stopping installation for 0.0.7a

### ISSUE THREAD

**Issue by sagaciouszu** [swetoast/steamlink-launcher#23]
There's an errant quotation in line 4 of addon.xml that stops installation on OSMC.

`    <import addon="xbmc.python" version="3.0.0""/>`

Removing the errant one,

`    <import addon="xbmc.python" version="3.0.0"/>`

and the install passes with no errors.

**Comment by swetoast** [comment]
havent pushed a new version but you can always use master for the fix will push when i got some time over
