### ISSUE TITLE
deb url is wrong

### ISSUE THREAD

**Issue by workingmanrob** [swetoast/steamlink-launcher#24]
Had to change the url in the addon.py script to pull the package.

http://media.steampowered.com/steamlink/rpi/steamlink.deb - in the script = 404

http://media.steampowered.com/steamlink/rpi/latest/steamlink.deb - works

Unfortunately the package install stopped at - Do you want to continue? [Y/n] and I have no keyboard connected but I assume things will work now once I find one and press Y.

Thanks for the nifty launcher.

**Comment by swetoast** [comment]
Hi

Thanks for bringing this to my attention, a new version is uploaded
