### ISSUE TITLE
YurchenkoSt's Addon.xml Fix Not Merged into Release v0.0.9

### ISSUE THREAD

**Issue by cwilhelmsen** [swetoast/steamlink-launcher#25]
YurchenkoSt provided a fix to the Error reading Attributes issue when attempting to install the Add-on from the compiled zip.  Looks like the second quote on line 4 is still present in my fresh DL of the compiled 0.0.9. For what it's worth the version for the plugin.program.steamlink is still 0.0.7a too.

**Comment by swetoast** [comment]
@swetoast swetoast merged commit 818101b into swetoast:master 15 days ago

**Comment by swetoast** [comment]
i updated the zip and tried it myself and it installed without issues

**Comment by cwilhelmsen** [comment]
Just nabbed the new zip and installed it. Fix confirmed.
