### ISSUE TITLE
Fails to install on OSMC Build for RPi4

### ISSUE THREAD

**Issue by Hainswof** [swetoast/steamlink-launcher#26]
Build link: http://download.osmc.tv/installers/diskimages/v19testing/OSMC_TGT_vero3_20210414.img.gz

Process I followed:
1) Install above OSMC image onto fresh MicroSD card (Samsung 64GB)
2) Insert MicroSD card into RPi4 (Model 8GB)
3) Updated OSMC from it's internal updater
4) Attempted to install steamlink-launcher v0.0.9 - error installing

Error message: "Failed to install due to an invalid structure"

**Comment by swetoast** [comment]
yeah i know will fix

same as

https://github.com/swetoast/steamlink-launcher/issues/25

**Comment by swetoast** [comment]
also im not sure if rpi4 will work well since it doesnt have hardware acceleration so if there is performance issues i have no way to fix that

**Comment by swetoast** [comment]
again im not supporting rpi4 since its not supported by steam unless @slouken gives the thumbs up

**Comment by Hainswof** [comment]
> also im not sure if rpi4 will work well since it doesnt have hardware acceleration so if there is performance issues i have no way to fix that

@swetoast - steamlink works very well on RPi4 running the latest Raspberry Pi OS. 

I was simply hoping for a method that would avoid me having to manually swap SD cards each time one would like to go from  using OSMC and then like to play SteamLink.

Regardless, I appreciate what you have done creating this plugin for others that are using the correctly supported hardware. :)

**Comment by slouken** [comment]
> again im not supporting rpi4 since its not supported by steam unless @slouken gives the thumbs up

thumbs up :)

**Comment by swetoast** [comment]
@Hainswof retry the zip it should work

**Comment by swetoast** [comment]
@slouken ill update the readme to include rpi4

**Comment by Hainswof** [comment]
@swetoast @swetoast - Thank you kindly to you both!

I can confirm it now installs :)

A New Challenge Emerges:
When launching the app we get the following screen (attached)
![RPi4-Steamlink-Launcher-AfterLaunch](https://user-images.githubusercontent.com/71372605/117371239-a6a8f300-af1b-11eb-8502-60763d9d9fe9.png)

Pressing Enter at this stage exits back to OSMC.

**Comment by Hainswof** [comment]
UPDATE:
I managed to solve the above challenge by connecting via SSH and enter the following command:

sudo apt-get install gnupg

Now when launching the SteamLink app we get the following:
![image](https://user-images.githubusercontent.com/71372605/117378092-d7dbf000-af28-11eb-85e5-60259b026891.png)

Pressing Enter at this stage, once again, exits back to OSMC.

**Comment by Hainswof** [comment]
UPDATE:
I have tried _commenting out_ the line mentioned in the about output (#dtoverlay=vc4-kms-v3d)

However when rebooting OSMC gives us a sad face:
![20210507_114934](https://user-images.githubusercontent.com/71372605/117382316-59844b80-af32-11eb-9575-7bbf32567b3d.jpg)

I have also tried changing the line of code from:
dtoverlay=vc4-kms-v3d,cma-512
to
dtoverlay=vc4-fkms-v3d,cma-512

This gets us booting correctly into OSMC again and also past the "dtoverlay=vc4-kms-v3d" challenge.

However, with this configuration, SteamLink Launcher while it looks like it's about to launch correctly (going through it's TXT output like before), it simply exits itself now, back to OSMC before it gets any further.

**Comment by swetoast** [comment]
Will look at it this weekend

**Comment by swetoast** [comment]
keep the reports coming with your findings cause i dont have an rpi4

**Comment by swetoast** [comment]
@Hainswof looks like the rpi4 itselt has some issue with blank screens etc releated to the kernel gonna investigate see if i can borrow or pick up a rpi4 to experiment with.

**Comment by Hainswof** [comment]
> @Hainswof looks like the rpi4 itselt has some issue with blank screens etc releated to the kernel gonna investigate see if i can borrow or pick up a rpi4 to experiment with.
> 
> * added gnupg to the launcher for next release

Brilliant! Thank you kindly for your willingness to solve this challenge for all those in the same boat as us 🙏

Let me know if you would like me to test anything for you and give feedback, I will gladly help

**Comment by swetoast** [comment]
Keep hacking away at it and if you find anything post it to this thread meanwhile ill hunt for a rpi4 either pick up or borrow one you can ask @samnazarko for pointers in OSMC

**Comment by swetoast** [comment]
@Hainswof 

grab-logs -A

mind posting those after it crashes that would be of great help

**Comment by swetoast** [comment]
common theme when it crashes is 

```
[   25.687618] vc4_hdmi fef05700.hdmi: ASoC: error at snd_soc_dai_startup on fef05700.hdmi: -19
[   25.688259] vc4_hdmi fef05700.hdmi: ASoC: error at snd_soc_dai_startup on fef05700.hdmi: -19
[  131.647063] vc4_hdmi fef05700.hdmi: ASoC: error at snd_soc_dai_startup on fef05700.hdmi: -19
[  131.647631] vc4_hdmi fef05700.hdmi: ASoC: error at snd_soc_dai_startup on fef05700.hdmi: -19
```

need to investigate what that error is

**Comment by swetoast** [comment]
added a thread at osmc forums

https://discourse.osmc.tv/t/race-condition-in-the-rpi4-kernel/89371

**Comment by swetoast** [comment]
Closing this bug since its limited to OSMC itself and not the launcher, all you can do @Hainswof is wait for @samnazarko to update the kernel

**Comment by Hainswof** [comment]
> Closing this bug since its limited to OSMC itself and not the launcher, all you can do @Hainswof is wait for @samnazarko to update the kernel

I understand.

Thank you kindly for your help so far in this @swetoast - really appreciated 🙏

**Comment by samnazarko** [comment]
Our kernel is very recent -- so it's not an OSMC issue.

**Comment by swetoast** [comment]
Techically its kernel issue so like sam said on the forums just wait for the patch to be merged upstreams then trickle down to OSMC then you will be gaming in no time :)

**Comment by Hainswof** [comment]
Brilliant - thank you both for your help @swetoast and @samnazarko 😁

Looking forward to it 🎮

**Comment by cwilhelmsen** [comment]
Yup, thanks to all of you for your hard work on this!

**Comment by flos06** [comment]
Is there any way to see if/when it gets merged? Or should I just try every time there is an OSMC update?

**Comment by xsellier** [comment]
Any news on that, still having, but the kernel has been patched ever since.

**Comment by swetoast** [comment]
Provide logs on the OSMC forum board is better then asking around it here, waiting for a patch myself

**Comment by xsellier** [comment]
Posted on the osmc forum:
https://discourse.osmc.tv/t/rpi-4-steamlink-doesnt-work/91134
