### ISSUE TITLE
Fails on newest stable release of OSMC (2021.08-1)

### ISSUE THREAD

**Issue by linuxissuper** [swetoast/steamlink-launcher#28]
Fails to start with the following message:    
```
You have dtoverlay=vc4-kms-v3d in /boot/config.txt, which will cause a black screen when starting streaming - aborting.
Try commenting out that line and rebooting.
```
      
But when I do this, OSMC fails to start

**Comment by swetoast** [comment]
https://github.com/swetoast/steamlink-launcher/issues/26

**Comment by swetoast** [comment]
Open an issue on OSMC forums

**Comment by swetoast** [comment]
rpi4 has issues

**Comment by linuxissuper** [comment]
sorry, didn't see the existing issue     
but just to have it mentioned: I'm using raspberry pi 3b+

**Comment by protist** [comment]
I'm not sure if this is the same issue as the linked issue, as I'm using a Raspberry Pi 3B too. It's also a newer issue that (I think) relates to Steam Link's incompatibility with Kodi 19 (more discussion from @samnazarko [here](https://discourse.osmc.tv/t/steamlink-issues-with-kodi-19-and-bootloader-4-0-0/89990)).

Having said that, I think maybe the `vc4-kms-v3d` issues is with Steam Link, not the Steam Link Launcher itself, although the latter did get disabled in the Kodi 19 update.

**Comment by swetoast** [comment]
overlays etc is always osmc please open an issue on OSMC forums cant do much here for ya

**Comment by swetoast** [comment]
most of my issues with the kernel goes unfix by OSMC

**Comment by protist** [comment]
@swetoast No worries. Yeah, my link above was to the OSMC forums, but the suggestion there was that it was not a Kodi problem, so I guess implied it was a Steam issue… so maybe never to be fixed. I've stopped updating OSMC in the meantime unfortunately.
