### ISSUE TITLE
Steamlink won't launch on Kodi 19

### ISSUE THREAD

**Issue by lmlask** [swetoast/steamlink-launcher#29]
When running the addon:

```
You have dtoverlay=vc4-kms-v3d in /boot/config.txt, which will cause a black screen when starting streaming - aborting.
Try commenting out that line and rebooting.
```
If I comment out that line, OSMC won't boot properly (It'll just show the sad face continuously).

After some research I've found out this seems to happen in Kodi 19 even when launching steamlink from the console due to a new OSMC bootloader, but since this launcher was made specifically for Kodi 19 I'm wondering whether you guys thought of something.

**Comment by swetoast** [comment]
Yeah this is an osmc issue not a launcher issue

**Comment by slouken** [comment]
I believe this is fixed, once you install the DRI EGL drivers:
https://steamcommunity.com/app/353380/discussions/6/3193611900710760046/#c4328520278444207948

**Comment by swetoast** [comment]
tnx Sam for your assistance
