### ISSUE TITLE
zip file needed plugin directory

### ISSUE THREAD

**Issue by osakanataro** [swetoast/steamlink-launcher#3]
v0.0.4 could not install OSMC on raspbery pi 3.
plugin zip file needed "plugin.program.steamlink" directory.

I tried to modified zip file as follows
http://blog.osakana.net/sw/work/plugin.program.steamlink-v.0.0.4a.zip
this zip file work fine.

**Comment by swetoast** [comment]
done upped tnx, strangely enough on my rpi the zipped worked but hey you tested it and thats good enough for me :D
