### ISSUE TITLE
Video memory issue on Raspberry Pi 4

### ISSUE THREAD

**Issue by queequegaz** [swetoast/steamlink-launcher#36]
Fresh install of OSMC, and the steamlink-launcher appears to install without issue.  When trying to run, a command line pops up that says: `You are running with less than 128 MB video memory, you may need to go to the Raspberry Pi Configuration and increase your GPU memory.
Press enter to continue: `
There is no way to allocate memory to GPU in OSMC for the Pi 4 (my understanding is that GPU memory is dynamically allocated on the Pi 4, so the option is greyed out in the OSMC settings).

Is there a workaround for this that allows steam link to work on a Pi 4 with OSMC?  (In Raspberry PI OS, you can still allocate memory to GPU in the settings, and Steam Link works on the Pi 4).

Kodi version is 19.3

**Comment by swetoast** [comment]
Guess you didnt read the readme 

Known issues:

if these fixes are out of date and its working report back on the tracker.

RPI4 crashes in kernel with error message: vc4_hdmi fef05700.hdmi: ASoC: error at snd_soc_dai_startup on fef05700.hdmi

Status: Reported

    https://github.com/swetoast/steamlink-launcher/issues/26
    https://discourse.osmc.tv/t/race-condition-in-the-rpi4-kernel/89371

Doesnt matter about the video settings when the osmc kernel is broken

**Comment by queequegaz** [comment]
Apologies, I did read it but didn't realize this was the same/related issue.  Thank you for getting back to me.

**Comment by swetoast** [comment]
the bug in the readme crashes the kernel so it wont launch at all, been reporting on it but nothing is happening and the bug seems present in the rpi3 kernel also, the launcher works fine but steamlink crashes the kernel due to the bug with the OSMC kernel.

**Comment by swetoast** [comment]
anycase if you get it working report back cause im not tracking osmc updates anymore.
