### ISSUE TITLE
Steamlink Incompability

### ISSUE THREAD

**Issue by swetoast** [swetoast/steamlink-launcher#37]
@slouken hey i got an issue with Steamlink are you still working on Steamlink? 

https://discourse.osmc.tv/t/steamlink-issues-with-kodi-19-and-bootloader-4-0-0/89990/4

if so please read the link above and see if there is a possibility for a fix for Kodi 19 it kinda doesnt like overlays that Steamlink uses.

**Comment by nitropaul** [comment]
Is ther a version of osmc that steampunk does work with currently?

**Comment by swetoast** [comment]
None for rpi4 since they are all kodi 19

**Comment by nitropaul** [comment]
I am running a pi 3b

**Comment by swetoast** [comment]
Kodi 18.9, ask on the forum for futher support.

**Comment by slouken** [comment]
I was able to get Steam Link running on the latest OSMC image:
https://steamcommunity.com/app/353380/discussions/6/3193611900710760046/#c4328520278444207948
