### ISSUE TITLE
at least 128mb gpu mem required

### ISSUE THREAD

**Issue by wolfisberg** [swetoast/steamlink-launcher#38]
Hi

I'd love to test out the steamlink and since I'm already using osmc (on a pi 3B+), I came across your package. It (at least seems to) installs fine. But when running it, it says something like

> You need at least 128mb of gpu memory

and returns to osmc.

Now, in the pi config on osmc, allocating gpu memory manually is disabled (greyed out). Not sure if this used to be possible previously.

Doing some research it seems that osmc removed this option (recently?) and allocates gpu mem dynamically (or at least automatically) and there is no way to adjust it manually.

The only official info on steams side concerning compatibility that I found is this
https://help.steampowered.com/en/faqs/view/6424-467A-31D9-C6CB
And it says rpi 3B and 3B+ (but not 4, maybe because the article is older?). So, if Pi4 is not (officially) supported, and 3B+ does not have enough gpu mem, how can I even run your package?

Any help is appreciated, thank you!

Cheers.

**Comment by nitropaul** [comment]
Hi, i am wondering if I have the same issue as wolfisberg. Initially i did the upgrade route with OSMC to Matrix as Steamlink required python 3 and that wasnt supported on the version of OSMC i had installed. After upgrading through 'myOSMC', I installed SteamLink and it worked but I got no sound on any of the games on steamlink or media on OSMC. I did a fresh rebuild on a new sd card and now steamlink wont load past the message saying 'Press enter key' after the 'You need at least 128mb of gpu memory'. Here is a link to my system log. Not sure if it will help (also the first time have tried logs) Please bear with me. https://paste.osmc.tv/jaxahofema

**Comment by swetoast** [comment]
please paste config.txt

`cat /boot/config.txt`

**Comment by swetoast** [comment]
Use the wiki för guidance

https://osmc.tv/wiki/general/accessing-the-command-line/

if your unsure ask on the forums.

**Comment by nitropaul** [comment]
![image](https://user-images.githubusercontent.com/11235044/145065327-12a51e31-ffe8-43e1-a5a8-03fe215291a2.png)

**Comment by swetoast** [comment]
```
sudo -s 
echo "gpu_mem=128" >> cat /boot/config.txt
reboot
```

and try again thats how you add stuff to config.txt

**Comment by nitropaul** [comment]
I have tried adding that to the /boot/config.txt file, restarted (checked its in the config.txt) then tried running steamlink again. It does similar to before but no longer pauses to say press enter to continue, it just goes straight back into osmc.

**Comment by swetoast** [comment]
and that ties into the bug ive reported to valve atm steamlink is incompatible with kodi 19 with that osmc build

**Comment by swetoast** [comment]
closing this once since we cant get any futher steamlink needs a fix or else this launcher is dead.
