### ISSUE TITLE
Problem while installing

### ISSUE THREAD

**Issue by Kirjy** [swetoast/steamlink-launcher#4]
Installing on OSMC last version : 2 packages were required but not found : ldconfig and start-stop-daemon.
Then installation failed cause of this.

**Comment by swetoast** [comment]
you havent installed steamlink correctly this isnt a launcher issue

**Comment by Kirjy** [comment]
download the debian package and install it --> done
download the zip of the launcher and install it via Kodi --> done

I did these two operations twice with the same result.
This seems to be a launcher issue to me

**Comment by swetoast** [comment]
ldconfig etc is for installation the launcher contacts steamlink bin only.

**Comment by Kirjy** [comment]
Thanks for your answers. I look on steamlink to check whats wrong then
