### ISSUE TITLE
Crash on RPi 3B+

### ISSUE THREAD

**Issue by ChabaneAmaury** [swetoast/steamlink-launcher#40]
I don't know if this is related to the 3B+ itself, though I know Steamlink can run on it (I have done it before). When launching the app, it reload Kodi back to its startup point, just like if I just powered up the RPi (I have Plex set up to start as soon as Kodi starts, and every time it is starting again).
Let me know if I can provide any informations! (fresh installation of OSMC, nothing installed beside Plex add-on).

**Comment by swetoast** [comment]
Should be fixed in version 0.0.12
