### ISSUE TITLE
Required to manually input code to install dependencies

### ISSUE THREAD

**Issue by chugelmann** [swetoast/steamlink-launcher#44]
After placing the zip on my SD card and installing through OSMC, I attempted to open Steamlink Launcher, and was told I had to manually input "dpkg --configure -a" in order to be able to install dependencies needed for Steamlink Launcher. This also required me to use superuser to actually invoke that code. OSMC is a fresh install, only add-on is Plex. I cannot remember the dependencies, but it looked to be 4 or 5 separate things that needed to be installed before Steamlink Launcher would open.

**Comment by swetoast** [comment]
provide logs makes my work easier, dont think its the launcher at all when you have to perform `dpkg --configure -a` its a stalled installation from before

**Comment by chugelmann** [comment]
> 

What files/logs would be best for you? Not sure what output to look for on my SD card.

**Comment by swetoast** [comment]
`grab-logs -A`

same as providing OSMC forums with logs

**Comment by chugelmann** [comment]
https://paste.osmc.tv/iweyalezac

**Comment by chugelmann** [comment]
I downloaded OSMC's installer "osmc-installer.exe", wrote to a formatted SD card, popped it in my Pi 3B+, loaded OSMC, then installed the Plex add-on from repository. Today, I tried to install Steamlink Launcher, downloaded the zip, put it in root directory of SD card, installed through OSMC GUI, kept crashing OSMC until I was finally able to see it hang on the command line saying that it needed a bunch of dependencies that I did not have, and couldn't get without running "dpkg --configure -a" through SSH.

**Comment by chepe263** [comment]
Does setting `gpu_mem` in the [boot config](https://www.raspberrypi.com/documentation/computers/config_txt.html#gpu_mem) make a positive change?

**Comment by FF-AntiK** [comment]
same here

**Comment by swetoast** [comment]
https://github.com/swetoast/steamlink-launcher/issues/57
