### ISSUE TITLE
Blackscreen stream on 4K/UHD display

### ISSUE THREAD

**Issue by yusf** [swetoast/steamlink-launcher#48]
I'm running OSMC on a Pi 4. When Steam Link with the launcher the display reports resolution 3840×2160p. It does not matter what resolution OSMC was set to use prior to launching Steam Link. It always switches to 2160p. The Steam Link client or host, whatever it is, doesn't like that and display a black screen instead. Sound comes through fine, and the stream stats looks good.

I tried Steam Link on Raspbian to troubleshoot and that it worked well (though that was Debian Bullseye). 

I've also tried to limit the stream resolution in the streaming settings to no avail. Thus it really seems like the issue lies with the chosen 2160p resolution chosen by Steam Link.

Can the launcher force a maximum of 1080p somehow?

**Comment by yusf** [comment]
This was actually an issue with `dtoverlay=vc4-kms-v3d` in `config.txt`, that needed to be changed to `dtoverlay=vc4-fkms-v3d,cma-512` (notice the f). 🙌

**Comment by swetoast** [comment]
added to readme, tnx for the followup

**Comment by swetoast** [comment]
https://discourse.osmc.tv/t/black-steam-link-stream-on-pi-4/93202

**Comment by swetoast** [comment]
ask away on the forums leaving osmc support for the os devs

**Comment by swetoast** [comment]
Doubt you can dual overlays etc since this is out of the scope for the project that is why i dont handle it

**Comment by yusf** [comment]
Got it. Sorry 4 the spam. 😬

**Comment by swetoast** [comment]
No worries :)
