### ISSUE TITLE
This is unusable in multiple ways

### ISSUE THREAD

**Issue by allstar87** [swetoast/steamlink-launcher#51]
Okay, so, installed 1.0.12 or whatever from .zip on the most recent version of OSMC on my Pi 4 4GB model.  And it's just problem after problem after problem.

It starts up into a terminal that wants me to "press Enter to continue."  This is a media center installed on my TV in front of my couch, I don't have a keyboard attached to this machine, who on earth has a keyboard attached to an OSMC machine, this should never happen.

The installer fails unless you SSH into the box and run sudo dpkg --configure -a.  Glad I know how to do that.  This is 0/10 usability though, this is why people say Linux gaming doesn't work.

And now, I get it "working," I still have to have a keyboard attached to the machine to "press Enter to continue" every time it launches, which is kind of telling me this is a lost cause, but I actually get into Steam Link, I can connect to my machine, but when it actually starts streaming video, I get a black screen on my Pi.  Sound, but no video.

This is completely unusable.

**Comment by swetoast** [comment]
then crete one yourself
