### ISSUE TITLE
No audio in Steam Link app

### ISSUE THREAD

**Issue by RaraCool** [swetoast/steamlink-launcher#54]
Hello, I am aware that it's generally not advised to raise an issue here with the Steam Link app, however due to the locked down nature of OSMC, I don't think I would get much help in the Steam forums about this, and given that it is only in Steam Link and not Kodi, I'm not sure how much the OSMC forums would be able to help.

I got this Add-On, and got remote play working fairly quickly, with minimal latency. However, audio is not working in the Steam Link app. I know it is not an issue with my PC because my audio is fine when streaming to my phone, and none of the UI sounds in the Steam Link app before even streaming anything work either. I have tried fresh-installing OSMC and this Add-On to no avail. Is Steam Link expecting a different audio framework to what OSMC is using? What can I change in OSMC to have it mesh well?

Log: https://paste.osmc.tv/yilezuduci

Again, apologies if this is the wrong place to raise this issue. If you could point me in the right direction for where to find a solution I'd be very grateful.

**Comment by RaraCool** [comment]
I am on a Raspberry Pi 4 running the latest version of OSMC, after a fresh install.

**Comment by swetoast** [comment]
Hey i would highly recommend raising this issue on the steam forums due it being the app thats having the issue under a rpi4 so far the thing ive noticed is that the rpi4 model has been really inconsistent with steamlink, been a mess honestly :)

**Comment by swetoast** [comment]
not that i dont mind looking at a problem but the launcher itself does nothing else then launches the program so its basically 

run steamlink then exit

**Comment by RaraCool** [comment]
I see, I didn't know there were previous issues with the RPi4 specifically, thanks for that! Part of the reason I asked here was because the Add-On installs Steam Link, so I wasn't sure if there were any missing dependencies or anything. Thanks for your quick reply!

**Comment by swetoast** [comment]
np, steam forums is where i generally want people to go for support unless the launcher doesn't launch the program
