### ISSUE TITLE
Steam Controller issue

### ISSUE THREAD

**Issue by RunningX** [swetoast/steamlink-launcher#55]
Steam Controller wont Pair.

I used Steam Controller before on Raspbian with Steamlink on the same Raspberry. I Installed OSMC with this Add-on and the Controller is already paired, but with wrong mapping and not recognized on Steam (Host).  Its like Keyboard input.

I paired the controller with my PC after that i cant re-pair it on the Raspberry Pi SteamLink app.

when i connected the controller via USB the is every Button press doubled.

**Comment by swetoast** [comment]
Dunno never ran with the Steam Controller i own one but mapping is always wrong when adding it to any X guess the best course here is too seek guidance on steam forum since the addon doesn't control any controller related it just launches steamlink
