### ISSUE TITLE
Error when installing during removal of OSMC components

### ISSUE THREAD

**Issue by BenCearlock** [swetoast/steamlink-launcher#56]
I was able to get this working properly once previously, but had to reinstall OSMC and now the installer isn't completing the install process.  It appears to be trying to remove core OSMC components. 

Log started: 2023-09-11  16:30:22
Removing rbp4-device-osmc (1.1.3) ...
WARNING: You have tried to remove a package that is essential to OSMC's operation.
To undo these changes, run 'sudo apt-get -f install'.
dpkg: error processing package rbp4-device-osmc (--remove):
 installed rbp4-device-osmc package pre-removal script subprocess returned error exit status 1
dpkg: too many errors, stopping
Errors were encountered while processing:
 rbp4-device-osmc
Processing was halted because there were too many errors.
Log ended: 2023-09-11  16:30:22

I'm on a 8GB Pi4.

**Comment by swetoast** [comment]
your  previous installation never completed so your new installations are broken,

rbp4-device-osmc <--- osmc system not  steamlink

**Comment by BenCearlock** [comment]
> your previous installation never completed so your new installations are broken,
> 
> rbp4-device-osmc <--- osmc system not steamlink

Sorry for bothering... I've done a fresh install of OSMC and tried the launcher again, but still fail out when trying to remove rbp4-device-osmc (because it's a core component, according to the message).  I've updated and upgraded so I have no errors or anything hanging out waiting, but still get failure.

I know you said it's on osmc side, but osmc apt says everything is good so far as I can tell, and it's the steamlink installer that appears to be trying to remove rbp4-device-osmc. (I even tried to remove it manually but was blocked that way also.)

I'd love to get this figured out and archived for the knowledge base. Even if it's dumb user error, there are no shortage of us out there.

**Comment by swetoast** [comment]
fair enough dont get why the steamlink package would  uninstall  base system files, again out of scope for the launcher and more aimed at steam, seek support at valve forums
