### ISSUE TITLE
Create a "lackluster" libreelec addon

### ISSUE THREAD

**Issue by swetoast** [swetoast/steamlink-launcher#6]
https://forum.libreelec.tv/thread/14643-adding-steamlink-to-v9-0-0/

**Comment by noenthu** [comment]
@swetoast have you had any luck getting this addon to work with libreelec and the pi4? I was able to get the installation completed including the libs from buster. However, I could not get the steamlink to work (tried both through your shell script over ssh or through the modified addon script). The error was always something related to pulseaudio and the "service already running"

**Comment by swetoast** [comment]
@noenthu havent begun doing anything for libreelec only added this as a reminder will take a look at it  as soon as work doesnt take the overhand :) until then my advice is seek support on the thread on the libreelec forum

**Comment by swetoast** [comment]
@noenthu not even sure the RPI4 is supported since its a diffrent soc i would advice seeking support on steam forums for rpi4

**Comment by swetoast** [comment]
Closing this issue since it will be coming with next version
