### ISSUE TITLE
404 error during install

### ISSUE THREAD

**Issue by hackadelic** [swetoast/steamlink-launcher#60]
There is a 404 error during the install of something shows html output of a file failing followed by 2 enter presses to get back to kodi screen.. do I need to do anything differently? File was mail something I think

**Comment by hackadelic** [comment]
I tried running it again it tries to launch then goes to a terminal screen showing downloading update some html 404 not found nginx curl url using bad/illegal format or missing URL couldnt download archive, aborting update

**Comment by swetoast** [comment]
well we need an new update url to resolve that issue then :) mind finding out what steam moved it to ?

**Comment by swetoast** [comment]
@hackadelic 

http://media.steampowered.com/steamlink/rpi/latest/steamlink.deb

the one and only link in the script

isnt failing the deb file thats valves that one is the one that fails your bug report is misdirected.

**Comment by hackadelic** [comment]
Couldn't figure out how to get the output but this is what is on the screen I'm not sure how to get the initial message i tried reinstalling the addon.. it says starting steamlink then goes to that if I hit enter twice it goes back to osmc
![Screenshot_20241203_154018_Gallery](https://github.com/user-attachments/assets/040bb20c-76c0-4779-b469-4089d9150d71)

**Comment by swetoast** [comment]
Make a bug report with valve since its their deb file thats broken
