### ISSUE TITLE
ldconfig and start-stop-daemon missing during launcher install

### ISSUE THREAD

**Issue by taubel** [swetoast/steamlink-launcher#7]
Apparently in file `steamlink-launcher.sh` during `su osmc` some environment variables are lost, in my case `/sbin` was lost from `$PATH`. Because of this `/sbin/ldconfig` and `/sbin/start-stop-daemon` are not reachable

Changing `su osmc` to `su - osmc` fixed this

**Comment by swetoast** [comment]
fixed
