### ISSUE TITLE
PATH not correct when launching steamlink

### ISSUE THREAD

**Issue by slouken** [swetoast/steamlink-launcher#9]
Launching Steam Link for the first time fails because the path isn't set correctly, /sbin and /usr/sbin are not in the path, so package installation fails.

**Comment by swetoast** [comment]
```bash
$ which steamlink
/usr/bin/steamlink
```

so we need a variable in that cause my steamlink is at this location

**Comment by slouken** [comment]
This is a duplicate of this bug, and presumably his fix will work:
https://github.com/swetoast/steamlink-launcher/issues/7

**Comment by swetoast** [comment]
yepp but yours makes sense :P ill get around to fixing it so it looks up where steamlink is located aand then launches it and ill fix the other issue with missing group

**Comment by slouken** [comment]
The problem is not that steamlink isn't found, it's that steamlink's package installation fails, because /sbin and /usr/sbin aren't in the path. Package installation fails with the error message listed in the other bug, and steamlink Qt initialization fails with missing libraries.

I think sudo - osmc is the right fix.

**Comment by swetoast** [comment]
updated the launcher its on version 19 for kodi however its easily changed by modifying the line 

https://github.com/swetoast/steamlink-launcher/blob/master/plugin.program.steamlink/addon.xml#L4

to kodi 18.5 dont remember exactly what version that was but it should be in the old plugin xml file

let me know if the fixed ive added works

**Comment by slouken** [comment]
Here's a version that works for me, including downloading and installing Steam Link:
`
"""Steamlink Launcher for OSMC"""
import os
import xbmc
import xbmcgui
import xbmcaddon

__plugin__ = "steamlink"
__author__ = "toast"
__url__ = "https://github.com/swetoast/steamlink-launcher/"
__git_url__ = "https://github.com/swetoast/steamlink-launcher/"
__credits__ = "toast"
__version__ = "0.0.5"

dialog = xbmcgui.Dialog()
addon = xbmcaddon.Addon(id='plugin.program.steamlink')

def main():
    """Main operations of this plugin."""
    create_files()
    output = os.popen("sh /tmp/steamlink-launcher.sh").read()
    dialog.ok("Starting Steamlink", output)
    #print output

def create_files():
    """Creates bash files to be used for this plugin."""
    with open('/tmp/steamlink-launcher.sh', 'w') as outfile:
        outfile.write('#!/bin/bash\n'
                      'sudo openvt -c 7 -s -f clear\n'
                      'if [ ! -f /usr/bin/steamlink ]; then curl -o /tmp/steamlink.deb -#Of http://media.steampowered.com/steamlink/rpi/steamlink.deb; sudo dpkg -i /tmp/steamlink.deb; rm -f /tmp/steamlink.deb; fi\n'
                      'sudo su - osmc -c "sh /tmp/steamlink-watchdog.sh &" &\n'
                      'sudo su - osmc -c "nohup openvt -c 7 -f -s steamlink >/dev/null 2>&1 &" &\n'
                      'sudo openvt -c 7 -s -f clear\n'
                      'sudo su -c "systemctl stop mediacenter &" &\n'
                      'exit')
        outfile.close()
    with open('/tmp/steamlink-watchdog.sh', 'w') as outfile:
        outfile.write('#!/bin/bash\n'
                      'if [ "$HYPERIONFIX" = 1 ]; then if [ "$(pgrep hyperion)" ]; '
                      'then sudo service hyperion stop; fi; fi\n'
                      'sleep 8\n'
                      'if [ "$HYPERIONFIX" = 1 ]; then if [ ! "$(pgrep hyperion)" ]; then '
                      'sudo service hyperion start; fi; fi\n'
                      'while true; do VAR1="$(pgrep steamlink)"; if [ ! "$VAR1" ]; then\n'
                      'sudo openvt -c 7 -s -f clear; sudo su -c '
                      '"sudo systemctl restart mediacenter &" &\n'
                      'exit\n'
                      'fi\n'
                      'done\n'
                      'exit')
        outfile.close()
main()
`

**Comment by swetoast** [comment]
mind doing a pr ? kinda rushed today

**Comment by slouken** [comment]
Sure, sorry, that was messy. I'll do it properly.

**Comment by slouken** [comment]
Here you go! https://github.com/swetoast/steamlink-launcher/pull/11

**Comment by swetoast** [comment]
tnx will review after work thinking of using the tar.gz instead of the deb package this gives me greater control on where steamlink is installed so this launcher can work on both *elec and osmc installs but its a good first start towards that path
